/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.replanner;

import gui.Planner.*;
import dataTemplates.DataIssueTemplate;
import db.sqliteAllResults;
import guiImport.importJDialog;
import homeBackend.homePlanner;
import static homeBackend.mainRunning.dataReleaseDates;
import static homeBackend.mainRunning.list_resultPlanner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Didar
 */
public class replannerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form plannerJPanel
     */
    public replannerJPanel(ArrayList<DataIssueTemplate> tmpallIssueData) {
        initComponents();
        this.allIssueData = tmpallIssueData; 
        System.out.println("from the jpanel "+allIssueData.get(10).getStrKey());
        
        jSplitPane3.setVisible(false);
        jTableSolution1.setVisible(false);
        
        infoSolution1Panel.setVisible(false);
        infoSolution2Panel.setVisible(false);
//        infoSolution3Panel.setVisible(false);
        
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        
        
        
//        jLabel15.setVisible(false);
//        jLabel16.setVisible(false);
//        jLabel17.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField4FullTimeRes = new javax.swing.JTextField();
        jXDatePicker1startDate = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker1endDate = new org.jdesktop.swingx.JXDatePicker();
        replanInterval = new javax.swing.JComboBox<>();
        jComboBox1ftrRatio = new javax.swing.JComboBox<>();
        jComboBox2bugRatio = new javax.swing.JComboBox<>();
        jComboBox3impRatio = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1PartTimeRes = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        clearDBBtn = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSolution1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSolution2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        scrollpanecompare1 = new javax.swing.JScrollPane();
        compareTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        comparisonTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        oldplanTable = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2replan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        infoSolution1Panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        infoSolution2Panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jSplitPane1.setDividerLocation(300);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Generate Plan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        replanInterval.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "6", "8", "10", "12", "14", "16" }));

        jComboBox1ftrRatio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        jComboBox2bugRatio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        jComboBox3impRatio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Replanning date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Release end date");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Re plan interval");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Full-time resources");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("For feature (%)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("For bugs  (%)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("For improvement  (%)");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("ACO");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("SMPSO");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("NSGA II");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Choice of algorithms");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setText("Replanning View");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Part-time resources");

        jLabel17.setText("Allows to define changed status of a release");

        jLabel18.setText("and identify how replanning change request");

        jLabel19.setText("can benefit the release.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Allotment of available resources: ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Available human resources this release period:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Define the scope of the next release: ");

        clearDBBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearDBBtn.setText("Clear Plans");
        clearDBBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDBBtnActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Release start date");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4FullTimeRes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1PartTimeRes, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jXDatePicker1endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3impRatio, 0, 123, Short.MAX_VALUE)
                                    .addComponent(jComboBox2bugRatio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1ftrRatio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(replanInterval, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jXDatePicker1startDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(leftPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearDBBtn))
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(0, 25, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addGap(36, 36, 36))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(23, 23, 23)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker1startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXDatePicker1endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replanInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4FullTimeRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField1PartTimeRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addGap(11, 11, 11)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox1ftrRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2bugRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3impRatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox3)
                .addGap(12, 12, 12)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(clearDBBtn))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableSolution1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSolution1);

        jTabbedPane4.addTab("Solution 1", jScrollPane2);

        jTableSolution2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableSolution2);

        jTabbedPane4.addTab("Solution 2", jScrollPane3);

        jSplitPane2.setDividerLocation(450);

        compareTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollpanecompare1.setViewportView(compareTable1);

        jSplitPane2.setLeftComponent(scrollpanecompare1);

        comparisonTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(comparisonTable2);

        jSplitPane2.setRightComponent(jScrollPane4);

        jScrollPane5.setViewportView(jSplitPane2);

        jTabbedPane4.addTab("Solution comparison", jScrollPane5);

        jSplitPane4.setDividerLocation(450);

        oldplanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(oldplanTable);

        jSplitPane4.setLeftComponent(jScrollPane6);

        jTable2replan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable2replan);

        jSplitPane4.setRightComponent(jScrollPane7);

        jScrollPane1.setViewportView(jSplitPane4);

        jTabbedPane4.addTab("What if analysis", jScrollPane1);

        jSplitPane3.setDividerLocation(450);

        infoSolution1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solution 1 Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N
        infoSolution1Panel.setPreferredSize(new java.awt.Dimension(300, 80));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout infoSolution1PanelLayout = new javax.swing.GroupLayout(infoSolution1Panel);
        infoSolution1Panel.setLayout(infoSolution1PanelLayout);
        infoSolution1PanelLayout.setHorizontalGroup(
            infoSolution1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSolution1PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(infoSolution1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        infoSolution1PanelLayout.setVerticalGroup(
            infoSolution1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSolution1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(infoSolution1Panel);

        infoSolution2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solution 2 Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout infoSolution2PanelLayout = new javax.swing.GroupLayout(infoSolution2Panel);
        infoSolution2Panel.setLayout(infoSolution2PanelLayout);
        infoSolution2PanelLayout.setHorizontalGroup(
            infoSolution2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSolution2PanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(infoSolution2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        infoSolution2PanelLayout.setVerticalGroup(
            infoSolution2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoSolution2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(infoSolution2Panel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Date releaseStart = jXDatePicker1startDate.getDate();
        System.out.println(releaseStart.toString());
        Date releaseEnd = jXDatePicker1endDate.getDate(); 
        System.out.println(releaseStart.toString());
        
        long diff = releaseEnd.getTime() - releaseStart.getTime();
        int duration = (int)TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
        
        int fullTimeRes = Integer.parseInt(jTextField4FullTimeRes.getText());
        int partTimeRes = Integer.parseInt(jTextField1PartTimeRes.getText());
        int capacity = (fullTimeRes*8+partTimeRes*4)*duration;
        
        int featureRatio = Integer.parseInt((String)jComboBox1ftrRatio.getSelectedItem()); System.out.println(featureRatio);
        
        int bugRatio = Integer.parseInt((String)jComboBox2bugRatio.getSelectedItem()); System.out.println(bugRatio);
        int impRatio = Integer.parseInt((String)jComboBox3impRatio.getSelectedItem()); System.out.println(impRatio);
        int intreplanInterval = Integer.parseInt((String)replanInterval.getSelectedItem()); System.out.println(intreplanInterval);
        
        System.out.println(releaseStart.toString() + releaseStart.toString());
        System.out.println(capacity + " "+ featureRatio + " "+ bugRatio + " "+impRatio +" "+intreplanInterval);
        
        homePlanner obj_homePlanner;
		dataReleaseDates();
		
//		releaseStart=obj_ReleaseInfoCollection.getReleaseDate(4);
//		releaseEnd=obj_ReleaseInfoCollection.getReleaseDate(6);
//		obj_homePlanner = new homePlanner(releaseStart, releaseEnd, 6, allIssueData, 50000, 50, 30, 20); 
                
                obj_homePlanner = new homePlanner(releaseStart, releaseEnd, intreplanInterval, allIssueData, capacity, featureRatio, bugRatio, impRatio);
        try {
            list_resultPlanner = obj_homePlanner.runPlanner(false);
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.jButton1ActionPerformed()");
            Logger.getLogger(replannerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        jSplitPane3.setVisible(true);
        infoSolution1Panel.setSize(250, 130);
        infoSolution1Panel.setVisible(true);
        infoSolution2Panel.setSize(250, 130);
        infoSolution2Panel.setVisible(true);
        jTableSolution1.setVisible(true);
        
//        infoSolution3Panel.setVisible(true);
        
        jLabel9.setText("Total value: "+ Integer.toString(list_resultPlanner.get(0).totalValue));
        jLabel9.setVisible(true);
        jLabel10.setText("Total Distance: "+ Double.toString(list_resultPlanner.get(0).distance));
        jLabel10.setVisible(true);
        jLabel11.setText("Effort ratio (ftr, Bug, Imp ): "+ Integer.toString((int)list_resultPlanner.get(0).prpftrRatio) + " "+Integer.toString((int)list_resultPlanner.get(0).prpbugRatio)+" "+Integer.toString((int)list_resultPlanner.get(0).prpimpRatio));
        jLabel11.setVisible(true);
        
        String Query1 = "SELECT * FROM OfferedIssueData;";
        display1ExcelData (Query1); 
        String Query3 = "SELECT IssueKey, Summary, Offered FROM OfferedIssueData;";
        display3ExcelData (Query3); 
        display5ExcelData (Query3);
        
        if (list_resultPlanner.size()>1){
        
            jLabel12.setText("Total value: "+ Integer.toString(list_resultPlanner.get(1).totalValue));
            jLabel12.setVisible(true);
            jLabel13.setText("Total Distance: "+ Double.toString(list_resultPlanner.get(1).distance));
            jLabel13.setVisible(true);
            jLabel14.setText("Effort ratio (ftr, Bug, Imp ): "+ Integer.toString((int)list_resultPlanner.get(1).prpftrRatio) + " "+Integer.toString((int)list_resultPlanner.get(1).prpbugRatio)+" "+Integer.toString((int)list_resultPlanner.get(1).prpimpRatio));
            jLabel14.setVisible(true);
        
            String Query2 = "SELECT * FROM OfferedIssueData1;";
            display2ExcelData (Query2); 
            String Query4 = "SELECT IssueKey, Summary, Offered FROM OfferedIssueData1;";
            display4ExcelData (Query4); 
        }
        
        String Query6 = "SELECT IssueKey, Summary, Offered FROM BUPOfferedIssueData;";
        display6ExcelData (Query6);
////        if (list_resultPlanner.size()>2){
//        
//            jLabel15.setText("Total value: "+ Integer.toString(list_resultPlanner.get(2).totalValue));
//            jLabel15.setVisible(true);
//            jLabel16.setText("Total Distance: "+ Double.toString(list_resultPlanner.get(2).distance));
//            jLabel16.setVisible(true);
//            jLabel17.setText("Effort ratio (ftr, Bug, Imp ): "+ Double.toString(list_resultPlanner.get(2).prpftrRatio) + " "+Double.toString(list_resultPlanner.get(2).prpbugRatio)+" "+Double.toString(list_resultPlanner.get(2).prpimpRatio));
//            jLabel17.setVisible(true);
////        }
       
        
        
        
        
//        String Query3 = "SELECT * FROM OfferedIssueData WHERE Offered LIKE \"offered in 3\";";
        
        
//        display3ExcelData (Query3); 

        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void clearDBBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDBBtnActionPerformed
        try {
            // TODO add your handling code here:

            Class.forName("org.sqlite.JDBC");
            Connection connection = DriverManager.getConnection("jdbc:sqlite:DB/BSQPLanner.DB.sqlite");//
            
            Statement statement = connection.createStatement();
            ResultSet resultset = statement.executeQuery("DELETE FROM \"main\".\"OfferedIssueData\";");
            
            Statement statement1 = connection.createStatement();
            ResultSet resultset1 = statement1.executeQuery("DELETE FROM \"main\".\"OfferedIssueData1\";");
            
            Statement statement2 = connection.createStatement();
            ResultSet resultset2 = statement1.executeQuery("DELETE FROM \"main\".\"BUPOfferedIssueData\";");
            
            connection.close();
            
        } catch (Exception ex) {
            Logger.getLogger(replannerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_clearDBBtnActionPerformed

public void display1ExcelData (String strQuery){
        try {    
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            if (!resultSet.next() ) {
                System.out.println("no data---------------------------------");
            }
            jTableSolution1.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.display1ExcelData()");
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void display2ExcelData (String strQuery){
        try {    
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            
            jTableSolution2.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.display2ExcelData()");
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void display3ExcelData (String strQuery){
        try {    
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            
            compareTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.display2ExcelData()");
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void display4ExcelData (String strQuery){
        try {    
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            
            comparisonTable2.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.display2ExcelData()");
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void display5ExcelData (String strQuery){
        try {    
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            
            jTable2replan.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.display2ExcelData()");
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void display6ExcelData (String strQuery){
        try {    
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            
            oldplanTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            System.out.println("gui.Planner.plannerJPanel.display2ExcelData()");
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


//public void display3ExcelData (String strQuery){
//        try {    
//            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
//           
//            jTableSolution3.setModel(DbUtils.resultSetToTableModel(resultSet));
//            obj_sqliteAllResults.closeConnection();
//            
//        } catch (Exception ex) {
//            System.out.println("gui.Planner.plannerJPanel.display3ExcelData()");
//            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearDBBtn;
    private javax.swing.JTable compareTable1;
    private javax.swing.JTable comparisonTable2;
    private javax.swing.JPanel infoSolution1Panel;
    private javax.swing.JPanel infoSolution2Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1ftrRatio;
    private javax.swing.JComboBox<String> jComboBox2bugRatio;
    private javax.swing.JComboBox<String> jComboBox3impRatio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable2replan;
    private javax.swing.JTable jTableSolution1;
    private javax.swing.JTable jTableSolution2;
    private javax.swing.JTextField jTextField1PartTimeRes;
    private javax.swing.JTextField jTextField4FullTimeRes;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1endDate;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1startDate;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTable oldplanTable;
    private javax.swing.JComboBox<String> replanInterval;
    private javax.swing.JScrollPane scrollpanecompare1;
    // End of variables declaration//GEN-END:variables

ArrayList<DataIssueTemplate> allIssueData; 
ResultSet resultSet = null;
sqliteAllResults obj_sqliteAllResults; 




}
