/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.home;


import dataTemplates.DataIssueTemplate;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import homeBackend.mainRunning;
import java.util.ArrayList;

/**
 *
 * @author Didar
 */
public class importJDialog extends javax.swing.JDialog {

    /**
     * Creates new form importJDialog
     */
    public importJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadButton.setEnabled(false);
        importSuccessJLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lineBorder1 = (javax.swing.border.LineBorder)javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        importBrowseJPanel = new javax.swing.JPanel();
        importJTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        importSuccessJLabel = new javax.swing.JLabel();
        ImportDatajScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        importBrowseJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        importBrowseJPanel.setToolTipText("");

        importJTextField.setText("Load your project file");

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        importSuccessJLabel.setText("jLabel1");

        javax.swing.GroupLayout importBrowseJPanelLayout = new javax.swing.GroupLayout(importBrowseJPanel);
        importBrowseJPanel.setLayout(importBrowseJPanelLayout);
        importBrowseJPanelLayout.setHorizontalGroup(
            importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                .addGroup(importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(importJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadButton))
                    .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(importSuccessJLabel)))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        importBrowseJPanelLayout.setVerticalGroup(
            importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(loadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importSuccessJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImportDatajScrollPane)
                    .addComponent(importBrowseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importBrowseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImportDatajScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        
         mainRunning obj_mainRunning = new mainRunning(); 
         obj_mainRunning.tokenizeFilePath (fileAddress); 
        obj_mainRunning.ReadingExcelsheet(allIssueData, 1, obj_mainRunning.strFilePath, obj_mainRunning.strFileName, obj_mainRunning.strFileName);
        System.out.println("++++"+allIssueData.get(10).getStrKey());
    }//GEN-LAST:event_loadButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
               if(f.isDirectory()){
                   return true;
               }else{
                  return  f.getName().toLowerCase().endsWith(".xlsx");
               }
            }

            public String getDescription() {
                return "Excel documents(*.xlsx)";
            }
        });
    
        int option = fc.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            
            fileAddress = fc.getSelectedFile().getPath(); 
            importJTextField.setText(fileAddress);

        }

        if (importJTextField.getText().isEmpty()) {
            loadButton.setEnabled(false);
        } else {
            loadButton.setEnabled(true);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                importJDialog dialog = new importJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ImportDatajScrollPane;
    private javax.swing.JButton browseButton;
    private javax.swing.JPanel importBrowseJPanel;
    private javax.swing.JTextField importJTextField;
    private javax.swing.JLabel importSuccessJLabel;
    private javax.swing.border.LineBorder lineBorder1;
    private javax.swing.JButton loadButton;
    // End of variables declaration//GEN-END:variables
    private String fileAddress= null; 
    ArrayList<DataIssueTemplate> allIssueData = new ArrayList<DataIssueTemplate> (); 



}
