/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiImport;


import dataTemplates.DataIssueTemplate;
import db.sqliteAllResults;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import homeBackend.mainRunning;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils; 


/**
 *
 * @author Didar
 */
public class importJDialog extends javax.swing.JDialog {

    /**
     * Creates new form importJDialog
     */
    public importJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadButton.setEnabled(false);
        importSuccessJLabel.setText("Saving the dataset in DB may take upto five minutes to upload");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lineBorder1 = (javax.swing.border.LineBorder)javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        importBrowseJPanel = new javax.swing.JPanel();
        importJTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        importSuccessJLabel = new javax.swing.JLabel();
        checkDatasetButton = new javax.swing.JButton();
        importProjectDisplayjScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        importBrowseJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        importBrowseJPanel.setToolTipText("");

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        importSuccessJLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        importSuccessJLabel.setForeground(new java.awt.Color(0, 51, 255));
        importSuccessJLabel.setText("jLabel1");

        checkDatasetButton.setText("Save in DB");
        checkDatasetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDatasetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout importBrowseJPanelLayout = new javax.swing.GroupLayout(importBrowseJPanel);
        importBrowseJPanel.setLayout(importBrowseJPanelLayout);
        importBrowseJPanelLayout.setHorizontalGroup(
            importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importSuccessJLabel)
                    .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                        .addComponent(importJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkDatasetButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        importBrowseJPanelLayout.setVerticalGroup(
            importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importBrowseJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importBrowseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(loadButton)
                    .addComponent(checkDatasetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importSuccessJLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(importProjectDisplayjScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(importBrowseJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importBrowseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importProjectDisplayjScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        
            // TODO add your handling code here:
            
          mainRunning obj_mainRunning = new mainRunning();
          obj_mainRunning.tokenizeFilePath (fileAddress);
          obj_mainRunning.ReadingExcelsheet(allIssueData, 1, obj_mainRunning.strFilePath, obj_mainRunning.strFileName, obj_mainRunning.strFileName);
          
          importSuccessJLabel.setText("Loaded records for this session"); 
          
          
    }//GEN-LAST:event_loadButtonActionPerformed

    public void insertExcelData (){
            try {
                
                Class.forName("org.sqlite.JDBC");
                connection = DriverManager.getConnection("jdbc:sqlite:DB/BSQPLanner.DB.sqlite");//
                String strQuery = "Insert into AllIssueData values (?,?,?,?,?,?);";
                PreparedStatement preparedStatement = connection.prepareStatement(strQuery); 

                for (int i=0;i<10;i++){
//                for (int i=0;i<allIssueData.size();i++){
                    
                    preparedStatement.setString(1, allIssueData.get(i).getStrKey());
                    preparedStatement.setString(2, allIssueData.get(i).getStrSummary());
                    preparedStatement.setString(3, allIssueData.get(i).getStrDescription());
                    preparedStatement.setString(4, allIssueData.get(i).getStrStatus());
                    preparedStatement.setString(5, allIssueData.get(i).getStrPriority());
                    preparedStatement.setString(6, allIssueData.get(i).getStrResolution());
                    
                    preparedStatement.executeUpdate();
                    importSuccessJLabel.setText("Importing record "+i+" of total "+ allIssueData.size()+ " records"); 
                    
                    
                }
                
                connection.close();
            }
            catch (Exception ex) {
                System.out.println("guiImport.importJDialog.insertExcelData()");
                Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
    }
    
    
    
    
    
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
               if(f.isDirectory()){
                   return true;
               }else{
                  return  f.getName().toLowerCase().endsWith(".xlsx");
               }
            }

            public String getDescription() {
                return "Excel documents(*.xlsx)";
            }
        });
    
        int option = fc.showOpenDialog(this);

        if (option == JFileChooser.APPROVE_OPTION) {
            
            fileAddress = fc.getSelectedFile().getPath(); 
            importJTextField.setText(fileAddress);

        }

        if (importJTextField.getText().isEmpty()) {
            loadButton.setEnabled(false);
        } else {
            loadButton.setEnabled(true);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void checkDatasetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDatasetButtonActionPerformed
        // TODO add your handling code here:
        
        
        insertExcelData (); 
        importSuccessJLabel.setText("Data uploaded in SQLite database successfully");
        
        
        obj_TableViewJPanel  = new TableViewJPanel  (); 
        importProjectDisplayjScrollPane1.setViewportView(obj_TableViewJPanel);
    }//GEN-LAST:event_checkDatasetButtonActionPerformed

     public ArrayList<DataIssueTemplate> getAllIssueData (){
         return allIssueData; 
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                importJDialog dialog = new importJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton checkDatasetButton;
    private javax.swing.JPanel importBrowseJPanel;
    private javax.swing.JTextField importJTextField;
    private javax.swing.JScrollPane importProjectDisplayjScrollPane1;
    private javax.swing.JLabel importSuccessJLabel;
    private javax.swing.border.LineBorder lineBorder1;
    private javax.swing.JButton loadButton;
    // End of variables declaration//GEN-END:variables
    private String fileAddress= null; 
    ArrayList<DataIssueTemplate> allIssueData = new ArrayList<DataIssueTemplate> (); 
    TableViewJPanel obj_TableViewJPanel; 
    Connection connection = null;
    Statement statement = null; 
    
}
