/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiImport;

import dataTemplates.DataIssueTemplate;
import db.sqliteAllResults;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Didar
 */
public class TableViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TableViewJPanel
     */
    public TableViewJPanel() {
        initComponents();
        displayExcelData (); 
    }

    
    
    
    
    public void displayExcelData (){
        try {    
            strQuery = "SELECT * FROM AllIssueData;";
            resultSet=obj_sqliteAllResults.getResults(strQuery, "DB/BSQPLanner.DB.sqlite");
            
            ImportedDataJTable.setModel(DbUtils.resultSetToTableModel(resultSet));
            obj_sqliteAllResults.closeConnection();
            
        } catch (Exception ex) {
            Logger.getLogger(importJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ImportedDataJTable = new javax.swing.JTable();
        importStatusJLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        ImportedDataJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ImportedDataJTable);

        importStatusJLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        importStatusJLabel.setForeground(new java.awt.Color(0, 51, 204));
        importStatusJLabel.setText("(For demo purpose we are displaying a subset of records from SQLite DB)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(importStatusJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(importStatusJLabel)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ImportedDataJTable;
    private javax.swing.JLabel importStatusJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    ArrayList<DataIssueTemplate> allIssueData; 
    String strQuery = null;
    ResultSet resultSet = null;
   
    sqliteAllResults obj_sqliteAllResults; 

}
